# Generated by Django 5.0.4 on 2024-04-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Management', '0002_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField(max_length=1000)),
                ('item_price', models.IntegerField()),
                ('item_photo', models.FileField(default='0', upload_to='media/photo')),
            ],
        ),
    ]
